#if defined(LANGUAGE_DX_DX) //SD cards will be translated to Ôzlaĉ
  #define TXT_BACK "<-"
  #define TXT_CLOCK "Goťâ"
  #define TXT_SETTINGS "Settings"
  #define TXT_NEVER "Never"
  #define TXT_SEC "seconds"
  #define TXT_MIN	"minutes"
  #define TXT_AUTO_DIM "SET AUTO DIM TIME"
  #define TXT_SET_BRIGHT "SET BRIGHTNESS"
  #define TXT_BATT_INFO "Battery Info"
  #define TXT_BRIGHT "Brightness"
  #define TXT_SET_CLOCK "Set Goťâ"
  #define TXT_ROTATION "Rotation"
  #define TXT_ABOUT "About"
  #define TXT_REBOOT "Reboot"
  #define TXT_CLR_SETTINGS "Clear Settings"
  #define TXT_CLRING_SETTINGS "Restoring Default\nSettings..."
  #define TXT_RIGHT "Tyun"
  #define TXT_LEFT "ťyan"
  #define TXT_UP "Up"
  #define TXT_BATT "Battery: "
  #define TXT_EXIT "Press any key to <-"
  #define TXT_RG_AMERICAS "Region:\nAmericas / Asia\n"
  #define TXT_RG_EMEA "Region: EMEA"
  #define TXT_SEL_GO_PAUSE "Sct: Go/Pause"
  #define TXT_SEL_EXIT "Next: <-"
  #define TXT_TRIG_TV "triggered TVBG"
  #define TXT_MN_AMERICA "Americas / Asia"
  #define TXT_MN_EMEA "EU/MidEast/Africa"
  #define TXT_REGION "Region"
  #define TXT_FK_GP "Front Key: Go/Pause"
  #define TXT_SET_HOUR "SET HOUR"
  #define TXT_SET_MIN "SET MINUTE"
  #define TXT_ADV "Advertising:\n"  
  #define TXT_SP_RND "Swift Pair Random"
  #define TXT_SEL_EXIT2 "\n\nNext: Exit"
  #define TXT_BT_SPAM "BT Spam"
  #define TXT_SA_CRASH "SourApple Crash"
  #define TXT_CMB_BT_SPAM " Combined BT Spam"
  #define TXT_AD_SPAM "Android Spam"
  #define TXT_AJ_TRANSF_NM "Transfer Number"
  #define TXT_AJ_TV_COLOR "TV Color Balance"
  #define TXT_STP_NW_PH "Setup New Phone"
  #define TXT_SA_ADV "SourApple Advertisement: "
  #define TXT_SP_ADV "SwiftPair Advertisement: '%s' - "
  #define TXT_AD_SPAM_ADV "Android Spam Advertisement: "
  #define TXT_AJ_ADV "AppleJuice Advertisement: "
  #define TXT_WF_SP "WiFi Spam"
  #define TXT_RND_SSID " - Random SSIDs\n"
  #define TXT_WF_SCAN "Scan Wifi"
  #define TXT_WF_SPAM_FUN "Spam Funny"
  #define TXT_WF_SPAM_RR "Spam Rickroll"
  #define TXT_WF_SPAM_RND "Spam Random"
  #define TXT_WF_RESCAN "[RESCAN]"
  #define TXT_WF_OPEN "Open"
  #define TXT_WF_CHANN "Chan : %d\n"
  #define TXT_WF_CRYPT "Crypt: %s\n"
  #define TXT_SEL_BACK "\nNext: Back\n"
  #define TXT_HOLD_CLONE "Hold Select: Clone\n"
  #define TXT_WF_SCN "WiFi Scan"
  #define TXT_WF_SCNING "Scanning..."
  #define TXT_INST_NXT "Next: Ar"
  #define TXT_INST_PRV "Prev: Al"
  #define TXT_INST_SEL "Sel : Enter or ->"
  #define TXT_INST_HOME "Home: Esc   or <- "
  #define TXT_INST_PRSS_KEY "         Press a key"
  #define TXT_STK_NXT "Next: Side Button"
  #define TXT_STK_SEL "Sel : M5 Button"
  #define TXT_STK_HOME "Home: Power Button"
  #define TXT_SDCARD "Mount/Unmount Ôzlaĉ"
  #define TXT_DEAUTH_START "Select>Start DEAUTH\n"
  #define TXT_DEAUTH_STOP "Select>Stop DEAUTH \n"
  #define TXT_HOLD_ATTACK "Hold Select: Attack\n"
  #define TXT_WFA_PORTAL "Clone Portal"
  #define TXT_WFA_DEAUTH "Deauth attack"
  #define TXT_WFA_COMBINED "Deauth+Clone"
  #define TXT_BLACK "Sôčun"
  #define TXT_NAVY "Navy"
  #define TXT_DARKGREEN "Dark Green"
  #define TXT_DARKCYAN "Dark Cyan"
  #define TXT_MAROON "Maroon"
  #define TXT_PURPLE "Purple"
  #define TXT_OLIVE "Olive"
  #define TXT_LIGHTGREY "Light Grey"
  #define TXT_DARKGREY "Dark Grey"
  #define TXT_BLUE "Tir"
  #define TXT_GREEN "Lôď"
  #define TXT_CYAN "Cyan"
  #define TXT_RED "Nur"
  #define TXT_MAGENTA "Magenta"
  #define TXT_YELLOW "Her"
  #define TXT_WHITE "Kâčun"
  #define TXT_ORANGE "Orange"
  #define TXT_GREENYELLOW "Lôd Her"
  #define TXT_PINK "Pink"
  #define TXT_COLOR "Custom Čun"
  #define TXT_SET_FGCOLOR "MAIN Čun"
  #define TXT_SET_BGCOLOR "BACKGROUND Čun"
  #define TXT_THEME "Čun Theme"
  #define TXT_TUNE "Tunes"
  #define TXT_TUNE_ON "Tunes ON"
  #define TXT_TUNE_OFF "Tunes OFF"
#endif

#if defined(LANGUAGE_EN_US)
  #define TXT_BACK "<-"
  #define TXT_CLOCK "Clock"
  #define TXT_SETTINGS "Settings"
  #define TXT_NEVER "Never"
  #define TXT_SEC "seconds"
  #define TXT_MIN	"minutes"
  #define TXT_AUTO_DIM "SET AUTO DIM TIME"
  #define TXT_SET_BRIGHT "SET BRIGHTNESS"
  #define TXT_BATT_INFO "Battery Info"
  #define TXT_BRIGHT "Brightness"
  #define TXT_SET_CLOCK "Set Clock"
  #define TXT_ROTATION "Rotation"
  #define TXT_ABOUT "Credits"
  #define TXT_REBOOT "Reboot"
  #define TXT_SHUTDOWN "Shut down"
  #define TXT_PWR_MENU "Power menu"
  #define TXT_CLR_SETTINGS "Clear Settings"
  #define TXT_CLRING_SETTINGS "Restoring Default\nSettings..."
  #define TXT_RIGHT "Right"
  #define TXT_LEFT "Left"
  #define TXT_UP "Up"
  #define TXT_BATT "Battery: "
  #define TXT_EXIT "Press any key to <-"
  #define TXT_RG_AMERICAS "Region:\nAmericas / Asia\n"
  #define TXT_RG_EMEA "Region: EMEA"
  #define TXT_SEL_GO_PAUSE "Sct: Go/Pause"
  #define TXT_SEL_EXIT "Next: <-"
  #define TXT_TRIG_TV "triggered TVBG"
  #define TXT_MN_AMERICA "Americas / Asia"
  #define TXT_MN_EMEA "EU/MidEast/Africa"
  #define TXT_REGION "Region"
  #define TXT_FK_GP "Front Key: Go/Pause"
  #define TXT_SET_HOUR "SET HOUR"
  #define TXT_SET_MIN "SET MINUTE"
  #define TXT_ADV "Advertising:\n"  
  #define TXT_SP_RND "Swift Pair Random"
  #define TXT_SEL_EXIT2 "\n\nNext: Exit"
  #define TXT_BT_SPAM "BT Spam"
  #define TXT_SA_CRASH "SourApple Crash"
  #define TXT_CMB_BT_SPAM " Combined BT Spam"
  #define TXT_AD_SPAM "Android Spam"
  #define TXT_AJ_TRANSF_NM "Transfer Number"
  #define TXT_AJ_TV_COLOR "TV Color Balance"
  #define TXT_STP_NW_PH "Setup New Phone"
  #define TXT_SA_ADV "SourApple Advertisement: "
  #define TXT_SP_ADV "SwiftPair Advertisement: '%s' - "
  #define TXT_AD_SPAM_ADV "Android Spam Advertisement: "
  #define TXT_AJ_ADV "AppleJuice Advertisement: "
  #define TXT_WF_SP "WiFi Spam"
  #define TXT_RND_SSID " - Random SSIDs\n"
  #define TXT_WF_SCAN "Scan Wifi"
  #define TXT_WF_SPAM_FUN "Spam Funny"
  #define TXT_WF_SPAM_RR "Spam Rickroll"
  #define TXT_WF_SPAM_RND "Spam Random"
  #define TXT_WF_RESCAN "[RESCAN]"
  #define TXT_WF_OPEN "Open"
  #define TXT_WF_CHANN "Chan : %d\n"
  #define TXT_WF_CRYPT "Crypt: %s\n"
  #define TXT_SEL_BACK "\nNext: Back\n"
  #define TXT_HOLD_CLONE "Hold Select: Clone\n"
  #define TXT_WF_SCN "WiFi Scan"
  #define TXT_WF_SCNING "Scanning..."
  #define TXT_INST_NXT "Next: Down Arrow"
  #define TXT_INST_PRV "Prev: Up Arrow"
  #define TXT_INST_SEL "Sel : Enter or ->"
  #define TXT_INST_HOME "Home: Esc   or <- "
  #define TXT_INST_PRSS_KEY "         Press a key"
  #define TXT_STK_NXT "Next: Side Button"
  #define TXT_STK_SEL "Sel : M5 Button"
  #define TXT_STK_HOME "Home: Power Button"
  #define TXT_SDCARD "Mount/Unmount SD"
  #define TXT_DEAUTH_START "Select>Start DEAUTH\n"
  #define TXT_DEAUTH_STOP "Select>Stop DEAUTH \n"
  #define TXT_HOLD_ATTACK "Hold Select: Attack\n"
  #define TXT_WFA_PORTAL "Clone Portal"
  #define TXT_WFA_DEAUTH "Deauth attack"
  #define TXT_WFA_COMBINED "Deauth+Clone"
  #define TXT_BLACK "Black"
  #define TXT_NAVY "Navy"
  #define TXT_DARKGREEN "Dark Green"
  #define TXT_DARKCYAN "Dark Cyan"
  #define TXT_MAROON "Maroon"
  #define TXT_PURPLE "Purple"
  #define TXT_OLIVE "Olive"
  #define TXT_LIGHTGREY "Light Grey"
  #define TXT_DARKGREY "Dark Grey"
  #define TXT_BLUE "Blue"
  #define TXT_GREEN "Green"
  #define TXT_CYAN "Cyan"
  #define TXT_RED "Red"
  #define TXT_MAGENTA "Magenta"
  #define TXT_YELLOW "Yellow"
  #define TXT_WHITE "White"
  #define TXT_ORANGE "Orange"
  #define TXT_GREENYELLOW "Green Yellow"
  #define TXT_PINK "Pink"
  #define TXT_COLOR "Custom Colors"
  #define TXT_SET_FGCOLOR "MAIN COLOR"
  #define TXT_SET_BGCOLOR "BACKGROUND COLOR"
  #define TXT_THEME "Color Theme"
  #define TXT_TUNE "Boot tune"
  #define TXT_TUNE_ON "Boot tunes ON"
  #define TXT_TUNE_OFF "Boot tunes OFF"
#endif

#if defined(LANGUAGE_RD_EN)
  #define TXT_BACK "<-"
  #define TXT_CLOCK "Clock"
  #define TXT_SETTINGS "Confs"
  #define TXT_NEVER "Nvr"
  #define TXT_SEC "secs"
  #define TXT_MIN	"mins"
  #define TXT_AUTO_DIM "AUTO DIM"
  #define TXT_SET_BRIGHT "Set brights"
  #define TXT_BATT_INFO "Batts Inf"
  #define TXT_BRIGHT "Brights"
  #define TXT_SET_CLOCK "Set Clock"
  #define TXT_ROTATION "Rotate"
  #define TXT_ABOUT "Creds"
  #define TXT_REBOOT "Reboot"
  #define TXT_SHUTDOWN "Turn off"
  #define TXT_PWR_MENU "Powr"
  #define TXT_CLR_SETTINGS "Clearconf"
  #define TXT_CLRING_SETTINGS "Retoing."
  #define TXT_RIGHT ">"
  #define TXT_LEFT "<"
  #define TXT_UP "^"
  #define TXT_BATT "Batts: "
  #define TXT_EXIT "any ky <-"
  #define TXT_RG_AMERICAS "Region:\nGuns / Anime\n"
  #define TXT_RG_EMEA "Region: EMEA"
  #define TXT_SEL_GO_PAUSE "Sct: Go/Pas"
  #define TXT_SEL_EXIT "Nxt: <-"
  #define TXT_TRIG_TV "trigd TVBG"
  #define TXT_MN_AMERICA "Guns/Anime"
  #define TXT_MN_EMEA "Soap/Bomb/Water"
  #define TXT_REGION "plce"
  #define TXT_FK_GP "Frnt Ky: Go/Paus"
  #define TXT_SET_HOUR "SET H"
  #define TXT_SET_MIN "SET MIN"
  #define TXT_ADV "Ads:\n"  
  #define TXT_SP_RND "Swft Par rand"
  #define TXT_SEL_EXIT2 "\n\nNxt: <-"
  #define TXT_BT_SPAM "BT Spm"
  #define TXT_SA_CRASH "Suraple Cras"
  #define TXT_CMB_BT_SPAM " Cmbnd Spm"
  #define TXT_AD_SPAM "Andr. Spm"
  #define TXT_AJ_TRANSF_NM "Trnsf Nums"
  #define TXT_AJ_TV_COLOR "TV Cllr Balnc"
  #define TXT_STP_NW_PH "Set Nw Phon"
  #define TXT_SA_ADV "SurAple Ad: "
  #define TXT_SP_ADV "SwftPar Ad: '%s' - "
  #define TXT_AD_SPAM_ADV "Adrod Spm Adv: "
  #define TXT_AJ_ADV "Apljuc Ads: "
  #define TXT_WF_SP "WiFi Spm"
  #define TXT_RND_SSID " - Rands SSIDs\n"
  #define TXT_WF_SCAN "Scn Wifi"
  #define TXT_WF_SPAM_FUN "Spm Fun"
  #define TXT_WF_SPAM_RR "Spm Ricks"
  #define TXT_WF_SPAM_RND "Spm Rands"
  #define TXT_WF_RESCAN "[RECAN]"
  #define TXT_WF_OPEN "Open"
  #define TXT_WF_CHANN "Chan : %d\n"
  #define TXT_WF_CRYPT "Crypt: %s\n"
  #define TXT_SEL_BACK "\nNxt: Back\n"
  #define TXT_HOLD_CLONE "Hld Select: Clone\n"
  #define TXT_WF_SCN "WiFi Scn"
  #define TXT_WF_SCNING "Scn..."
  #define TXT_INST_NXT "Nxt: "
  #define TXT_INST_PRV "Prev: ^"
  #define TXT_INST_SEL "Sel : Enter or <-"
  #define TXT_INST_HOME "Hme: Esc   or <- "
  #define TXT_INST_PRSS_KEY "         Prs a ky"
  #define TXT_STK_NXT "Next: Side"
  #define TXT_STK_SEL "Sel : M5"
  #define TXT_STK_HOME "Hme: Power"
  #define TXT_SDCARD "Mou/Unmo SD"
  #define TXT_DEAUTH_START "Slt>Start DETH\n"
  #define TXT_DEAUTH_STOP "Sltt>Stop DETH \n"
  #define TXT_HOLD_ATTACK "Hld Slc: Atk\n"
  #define TXT_WFA_PORTAL "Ptal"
  #define TXT_WFA_DEAUTH "Deth"
  #define TXT_WFA_COMBINED "Deth+Clon"
  #define TXT_BLACK "Black"
  #define TXT_NAVY "Navy"
  #define TXT_DARKGREEN "DarGreen"
  #define TXT_DARKCYAN "DarCyan"
  #define TXT_MAROON "Maroon"
  #define TXT_PURPLE "Purple"
  #define TXT_OLIVE "Olive"
  #define TXT_LIGHTGREY "LiGrey"
  #define TXT_DARKGREY "DarGrey"
  #define TXT_BLUE "Blue"
  #define TXT_GREEN "Green"
  #define TXT_CYAN "Cyan"
  #define TXT_RED "Red"
  #define TXT_MAGENTA "Magenta"
  #define TXT_YELLOW "Yellw"
  #define TXT_WHITE "Whte"
  #define TXT_ORANGE "Orange"
  #define TXT_GREENYELLOW "GreYellow"
  #define TXT_PINK "Pink"
  #define TXT_COLOR "Custom Colls"
  #define TXT_SET_FGCOLOR "MAIN COLL"
  #define TXT_SET_BGCOLOR "BACKGR COLL"
  #define TXT_THEME "ColL thm"
  #define TXT_TUNE "Boot tune"
  #define TXT_TUNE_ON "tunes ON"
  #define TXT_TUNE_OFF "tunes OFF"
#endif


#if defined(LANGUAGE_IT_IT)
  #define TXT_BACK "<-"
  #define TXT_CLOCK "Orologio"
  #define TXT_SETTINGS "Configurazione"
  #define TXT_NEVER "Mai"
  #define TXT_SEC "secondi"
  #define TXT_MIN	"minuti"
  #define TXT_AUTO_DIM "Luminosita Auto"
  #define TXT_SET_BRIGHT "IMPOSTA LUMINOSITA"
  #define TXT_BATT_INFO "Info Batteria"
  #define TXT_BRIGHT "Luminosita"
  #define TXT_SET_CLOCK "Imposta Ora"
  #define TXT_ROTATION "Rotazione"
  #define TXT_ABOUT "Info"
  #define TXT_REBOOT "Riavvio"
  #define TXT_CLR_SETTINGS "Canc. Settings"
  #define TXT_CLRING_SETTINGS "Ripristina Default\nSettings..."
  #define TXT_RIGHT "Destra"
  #define TXT_LEFT "Sinistra"
  #define TXT_BATT "Batteria: "
  #define TXT_EXIT "Premi un tasto per uscire"
  #define TXT_RG_AMERICAS "Regione:\nAmerica / Asia\n"
  #define TXT_RG_EMEA "Regione: EMEA"
  #define TXT_SEL_GO_PAUSE "Seleziona: Go/Pausa"
  #define TXT_SEL_EXIT "Prossimo: Esci"
  #define TXT_TRIG_TV "triggered TVBG"
  #define TXT_MN_AMERICA "America / Asia"
  #define TXT_MN_EMEA "EU/MidEast/Africa"
  #define TXT_REGION "Regione"
  #define TXT_FK_GP "Tasto Front.: Go/Pausa"
  #define TXT_SET_HOUR "IMPOSTA ORA"
  #define TXT_SET_MIN "IMPOSTA MINUTI"
  #define TXT_ADV "Avviso:\n"  
  #define TXT_SP_RND "Swift Pair Random"
  #define TXT_SEL_EXIT2 "\n\nProssimo: Esci"
  #define TXT_BT_SPAM "BT Spam"
  #define TXT_SA_CRASH "SourApple Crash"
  #define TXT_CMB_BT_SPAM "BT Spam Misto"
  #define TXT_AD_SPAM "Android Spam"
  #define TXT_AJ_TRANSF_NM "Transfer Number"
  #define TXT_AJ_TV_COLOR "TV Color Balance"
  #define TXT_STP_NW_PH "Setup New Phone"
  #define TXT_SA_ADV "SourApple Advertisement: "
  #define TXT_SP_ADV "SwiftPair Advertisement: '%s' - "
  #define TXT_AD_SPAM_ADV "Android Spam Advertisement: "
  #define TXT_AJ_ADV "AppleJuice Advertisement: "
  #define TXT_WF_SP "Spam WiFi"
  #define TXT_RND_SSID " - Random SSIDs\n"
  #define TXT_WF_SCAN "Scan Wifi"
  #define TXT_WF_SPAM_FUN "Spam Funny"
  #define TXT_WF_SPAM_RR "Spam Rickroll"
  #define TXT_WF_SPAM_RND "Spam Random"
  #define TXT_WF_RESCAN "[RIPETI SCANSIONE]"
  #define TXT_WF_OPEN "Apri"
  #define TXT_WF_CHANN "Canale : %d\n"
  #define TXT_WF_CRYPT "Crypt: %s\n"
  #define TXT_SEL_BACK "\nProssimo: Back\n"
  #define TXT_HOLD_CLONE "Tieni Premuto: Clone\n"
  #define TXT_WF_SCN "Scan WiFi"
  #define TXT_WF_SCNING "Scansione in corso..."
  #define TXT_INST_NXT "Prossimo: Down Arrow"
  #define TXT_INST_PRV "Precedente: Up Arrow"
  #define TXT_INST_SEL "Sel. : Enter or ->"
  #define TXT_INST_HOME "Home: Esc   or <- "
  #define TXT_INST_PRSS_KEY "Premi un tasto"
  #define TXT_STK_NXT "Avanti: Side Button"
  #define TXT_STK_SEL "Seleziona : M5 Button"
  #define TXT_STK_HOME "Home: Tasto Accensione"
  #define TXT_SDCARD "Mount/Unmount SD"
  #define TXT_DEAUTH_START "Seleziona>Start DEAUTH\n"
  #define TXT_DEAUTH_STOP "Seleziona>Stop DEAUTH \n"
  #define TXT_HOLD_ATTACK "Tieni Premuto: Attack\n"
  #define TXT_WFA_PORTAL "Clone Portal"
  #define TXT_WFA_DEAUTH "Deauth attack"
  #define TXT_WFA_COMBINED "Deauth+Clone"
  #define TXT_BLACK "Nero"
  #define TXT_NAVY "Blu Scuro"
  #define TXT_DARKGREEN "Verde Scuro"
  #define TXT_DARKCYAN "Ciano Chiaro"
  #define TXT_MAROON "Marrone"
  #define TXT_PURPLE "Viola"
  #define TXT_OLIVE "Olive"
  #define TXT_LIGHTGREY "Grigio Chiaro"
  #define TXT_DARKGREY "Grigio Scuro"
  #define TXT_BLUE "Blue"
  #define TXT_GREEN "Verde"
  #define TXT_CYAN "Ciano"
  #define TXT_RED "Rosso"
  #define TXT_MAGENTA "Magenta"
  #define TXT_YELLOW "Giallo"
  #define TXT_WHITE "Bianco"
  #define TXT_ORANGE "Arancio"
  #define TXT_GREENYELLOW "Giallo Verde"
  #define TXT_PINK "Rosa"
  #define TXT_COLOR "Colore Pers."
  #define TXT_SET_FGCOLOR "COLORE TESTO"
  #define TXT_SET_BGCOLOR "COLORE SFONDO"
  #define TXT_THEME "Tema Colori"
  #define TXT_TUNE "Tunes ON"
  #define TXT_TUNE_OFF "Tunes OFF"
#endif

#if defined(LANGUAGE_PT_BR)
  #define TXT_BACK "<-"
  #define TXT_CLOCK "Relogio"
  #define TXT_SETTINGS "Configuracoes"
  #define TXT_NEVER "Nunca"
  #define TXT_SEC "segundos"
  #define TXT_MIN	"minutos"
  #define TXT_AUTO_DIM "AJUSTAR LUZ DE FUNDO"
  #define TXT_SET_BRIGHT "BRILHO DA TELA"
  #define TXT_BATT_INFO "Estado da Bateria"
  #define TXT_BRIGHT "Brilho"
  #define TXT_SET_CLOCK "Ajustar Relogio"
  #define TXT_ROTATION "Rotacao"
  #define TXT_ABOUT "Sobre"
  #define TXT_REBOOT "Reiniciar M5"
  #define TXT_CLR_SETTINGS "Resetar Ajustes"
  #define TXT_CLRING_SETTINGS "Aplicando Ajustes\nPadrao..."
  #define TXT_RIGHT "Direita"
  #define TXT_LEFT "Esquerda"
  #define TXT_BATT "Bateria: "
  #define TXT_EXIT "Pressione qualquer tecla para sair"
  #define TXT_RG_AMERICAS "Regiao:\nAmericas / Asia\n"
  #define TXT_RG_EMEA "Regiao: EMEA"
  #define TXT_SEL_GO_PAUSE "Ok: Iniciar/Parar"
  #define TXT_SEL_EXIT "Seta 'v' : Sair"
  #define TXT_TRIG_TV "TVBG em funcionamento..."
  #define TXT_MN_AMERICA "Americas/Asia"
  #define TXT_MN_EMEA "EU/MidEast/Africa"
  #define TXT_REGION "Regiao"
  #define TXT_FK_GP "Botao Frontal:Iniciar/Pausar"
  #define TXT_SET_HOUR "AJUSTAR HORA"
  #define TXT_SET_MIN "AJUSTAR MINUTO"
  #define TXT_ADV "Aviso:\n"  
  #define TXT_SP_RND "Swift Pair Aleatorio"
  #define TXT_SEL_EXIT2 "\n\nProx: Sair"
  #define TXT_BT_SPAM "Bluetooth Spam"
  #define TXT_SA_CRASH "SourApple Crash"
  #define TXT_CMB_BT_SPAM "BT Spam Combinado"
  #define TXT_AD_SPAM "Android Spam"
  #define TXT_AJ_TRANSF_NM "Transferir Numero"
  #define TXT_AJ_TV_COLOR "Balanco de Cor TV"
  #define TXT_STP_NW_PH "Novo Aparelho"
  #define TXT_SA_ADV "Aviso SourApple: "
  #define TXT_SP_ADV "Aviso SwiftPair: '%s' - "
  #define TXT_AD_SPAM_ADV "Aviso Android Spam: "
  #define TXT_AJ_ADV "Aviso AppleJuice: "
  #define TXT_WF_SP "WiFi Spam"
  #define TXT_RND_SSID " - SSIDs Aleatorios\n"
  #define TXT_WF_SCAN "Escanear Wifi"
  #define TXT_WF_SPAM_FUN "Spam Engracado"
  #define TXT_WF_SPAM_RR "Spam Rickroll"
  #define TXT_WF_SPAM_RND "Spam Aleatorio"
  #define TXT_WF_RESCAN "[RESCANEAR]"
  #define TXT_WF_OPEN "Aberto"
  #define TXT_WF_CHANN "Canal: %d\n"
  #define TXT_WF_CRYPT "Cripto: %s\n"
  #define TXT_SEL_BACK "\nProx: Voltar\n"
  #define TXT_HOLD_CLONE "Segurar Ok: Clonar\n"
  #define TXT_WF_SCN "Escanear \n   Wifi"
  #define TXT_WF_SCNING "Escaneando..."
  #define TXT_INST_NXT "Prox: Seta v"
  #define TXT_INST_PRV "Anterior: Seta ^"
  #define TXT_INST_SEL "Sel : Ok ou Seta >"
  #define TXT_INST_HOME "Home: Esc ou Seta <"
  #define TXT_INST_PRSS_KEY "Pressione uma tecla"
  #define TXT_STK_NXT "Prox: Botao do Lado"
  #define TXT_STK_SEL "Sel : Botao M5"
  #define TXT_STK_HOME "Home: Botao Power"
  #define TXT_SDCARD "Monta/Desmonta SD"
  #define TXT_DEAUTH_START "Sel: Iniciar DEAUTH\n"
  #define TXT_DEAUTH_STOP "Sel: Parar DEAUTH  \n"
  #define TXT_HOLD_ATTACK "Segurar Ok: Atacar\n"
  #define TXT_WFA_PORTAL "Clonar Portal"
  #define TXT_WFA_DEAUTH "Ataque Deauth"
  #define TXT_WFA_COMBINED "Deauth+Clone"
  #define TXT_BLACK "Preto"
  #define TXT_NAVY "Azul Escuro"
  #define TXT_DARKGREEN "Verde Escuro"
  #define TXT_DARKCYAN "Ciano Escuro"
  #define TXT_MAROON "Vermelho Escuro"
  #define TXT_PURPLE "Roxo"
  #define TXT_OLIVE "Castanho"
  #define TXT_LIGHTGREY "Cinzo Claro"
  #define TXT_DARKGREY "Cinzo Escuro"
  #define TXT_BLUE "Azul"
  #define TXT_GREEN "Verde"
  #define TXT_CYAN "Ciano"
  #define TXT_RED "Vermelho"
  #define TXT_MAGENTA "Magenta"
  #define TXT_YELLOW "Amarelo"
  #define TXT_WHITE "Branco"
  #define TXT_ORANGE "Alaranjado"
  #define TXT_GREENYELLOW "Verde Amarelo"
  #define TXT_PINK "Rosa"
  #define TXT_COLOR "Mudar Cores"
  #define TXT_SET_FGCOLOR "COR PRINCIPAL"
  #define TXT_SET_BGCOLOR "COR DE FUNDO"
  #define TXT_THEME "Tema De Cores"
  #define TXT_TUNE "Tunes ON"
  #define TXT_TUNE_OFF "Tunes OFF"
#endif

#if defined(LANGUAGE_FR_FR)
  #define TXT_BACK "Retour"
  #define TXT_CLOCK "Horloge"
  #define TXT_SETTINGS "Parametres"
  #define TXT_NEVER "Jamais"
  #define TXT_SEC "secondes"
  #define TXT_MIN       "minutes"
  #define TXT_AUTO_DIM "REGLER LA BAISSE DE LUMINOSITE"
  #define TXT_SET_BRIGHT "REGLER LA LUMINOSITE"
  #define TXT_BATT_INFO "Infos batterie"
  #define TXT_BRIGHT "Luminosite"
  #define TXT_SET_CLOCK "Regler l'horloge"
  #define TXT_ROTATION "Rotation"
  #define TXT_ABOUT "A propos"
  #define TXT_REBOOT "Redemarrer"
  #define TXT_CLR_SETTINGS "Reinitialiser"
  #define TXT_CLRING_SETTINGS "Reinitialisation"
  #define TXT_RIGHT "Droite"
  #define TXT_LEFT "Gauche"
  #define TXT_BATT "Batterie: "
  #define TXT_EXIT "Pressez n'importe\nquelle touche pour\nquitter"
  #define TXT_RG_AMERICAS "Region:\nAmeriques / Asie\n"
  #define TXT_RG_EMEA "Region: EMEA"
  #define TXT_SEL_GO_PAUSE "Touche M5: Go/Stop"
  #define TXT_SEL_EXIT "Suivant: Quitter"
  #define TXT_TRIG_TV "TVBG en cours..."
  #define TXT_MN_AMERICA "Ameriques / Asie"
  #define TXT_MN_EMEA "EU/M-O/Afrique"
  #define TXT_REGION "Region"
  #define TXT_FK_GP "Touche M5: Go/Stop"
  #define TXT_SET_HOUR "REGLER L'HEURE"
  #define TXT_SET_MIN "REGLER LES MINUTES"
  #define TXT_ADV "Notification:\n"
  #define TXT_SP_RND "Swift Pair Aleatoire"
  #define TXT_SEL_EXIT2 "\n\nSuivant: Quitter"
  #define TXT_BT_SPAM "BT Spam"
  #define TXT_SA_CRASH "SourApple Crash"
  #define TXT_CMB_BT_SPAM " BT Spam Combine"
  #define TXT_AD_SPAM "Android Spam"
  #define TXT_AJ_TRANSF_NM "Transfert de Num."
  #define TXT_AJ_TV_COLOR "Colorimetrie TV"
  #define TXT_STP_NW_PH "Setup New Phone"
  #define TXT_SA_ADV "Notifications SourApple : "
  #define TXT_SP_ADV "Notifications SwiftPair : '%s' - "
  #define TXT_AD_SPAM_ADV "Notifications Android Spam: "
  #define TXT_AJ_ADV "AppleJuice : "
  #define TXT_WF_SP "WiFi Spam"
  #define TXT_RND_SSID " - SSIDs Aleatoires\n"
  #define TXT_WF_SCAN "Scan Wifi"
  #define TXT_WF_SPAM_FUN "Spam Funny"
  #define TXT_WF_SPAM_RR "Spam Rickroll"
  #define TXT_WF_SPAM_RND "Spam Aleatoire"
  #define TXT_WF_RESCAN "[RESCAN]"
  #define TXT_WF_OPEN "Ouvrir"
  #define TXT_WF_CHANN "Canal: %d\n"
  #define TXT_WF_CRYPT "Crypt: %s\n"
  #define TXT_SEL_BACK "\nSuivant: Retour\n"
  #define TXT_HOLD_CLONE "Touche M5: Cloner\n"
  #define TXT_WF_SCN "Scan WiFi"
  #define TXT_WF_SCNING "Scan..."
  #define TXT_INST_NXT "Suivant: Touche Bas"
  #define TXT_INST_PRV "Precedent: Touche Haut"
  #define TXT_INST_SEL "Sel : Entree ou ->"
  #define TXT_INST_HOME "Accueil: Echap ou <-"
  #define TXT_INST_PRSS_KEY "Pressez une touche"
  #define TXT_STK_NXT "Suivant: Touche Bas"
  #define TXT_STK_SEL "Select.: Touche M5"
  #define TXT_STK_HOME "Accueil: Touche M5"
  #define TXT_SDCARD "Monter/demont. SD"
  #define TXT_DEAUTH_START "Choix>Lancer DEAUTH\n"
  #define TXT_DEAUTH_STOP "Choix>Stopper DEAUTH \n"
  #define TXT_HOLD_ATTACK "Touche M5: Attaquer\n"
  #define TXT_WFA_PORTAL "Cloner Portail"
  #define TXT_WFA_DEAUTH "Attaque Deauth"
  #define TXT_WFA_COMBINED "Deauth+Clone"
  #define TXT_BLACK "Noir"
  #define TXT_NAVY "Bleu Marine"
  #define TXT_DARKGREEN "Vert Fonce"
  #define TXT_DARKCYAN "Cyan Fonce"
  #define TXT_MAROON "Marron"
  #define TXT_PURPLE "Violet"
  #define TXT_OLIVE "Olive"
  #define TXT_LIGHTGREY "Gris Clair"
  #define TXT_DARKGREY "Gris Fonce"
  #define TXT_BLUE "Bleu"
  #define TXT_GREEN "Vert"
  #define TXT_CYAN "Cyan"
  #define TXT_RED "Rouge"
  #define TXT_MAGENTA "Magenta"
  #define TXT_YELLOW "Jaune"
  #define TXT_WHITE "Blanc"
  #define TXT_ORANGE "Orange"
  #define TXT_GREENYELLOW "Jaune-Vert"
  #define TXT_PINK "Rose"
  #define TXT_COLOR "Choix des couleurs"
  #define TXT_SET_FGCOLOR "COULEUR PRINCIPALE"
  #define TXT_SET_BGCOLOR "COULEUR SECONDAIRE"
  #define TXT_THEME "Theme"
  #define TXT_TUNE "Tunes ON"
  #define TXT_TUNE_OFF "Tunes OFF"
#endif

